src/Entity/Patient.php
<?php

namespace App\Entity;

use App\Repository\PatientRepository;
use Doctrine\DBAL\Types\Types;
use Doctrine\ORM\Mapping as ORM;

#[ORM\Entity(repositoryClass: PatientRepository::class)]
#[ORM\HasLifecycleCallbacks]
class Patient
{
    #[ORM\Id]
    #[ORM\GeneratedValue]
    #[ORM\Column]
    private ?int $id = null;

    #[ORM\Column(length: 255)]
    private ?string $FirstName = null;

    #[ORM\Column(length: 255)]
    private ?string $LastName = null;

    #[ORM\Column]
    private ?int $Age = null;

    #[ORM\Column(type: Types::DATE_IMMUTABLE)]
    private ?\DateTimeImmutable $Date_naissance = null;

    #[ORM\Column(length: 255)]
    private ?string $Adresse = null;

    #[ORM\Column(type: Types::TEXT)]
    private ?string $Description = null;

    #[ORM\Column(type: Types::TEXT)]
    private ?string $Fiche_patient = null;

    #[ORM\Column]
    private ?\DateTimeImmutable $CreatedAt = null;

    #[ORM\Column]
    private ?\DateTimeImmutable $UpdatedAt = null;

    #[ORM\Column(length: 255)]
    private ?string $phone = null;

    public function __construct()
    {
        $this->CreatedAt = new \DateTimeImmutable();
        $this->UpdatedAt = new \DateTimeImmutable();
    }

    public function preUpdate()
    {
        $this->UpdatedAt = new \DateTimeImmutable();
    }

    public function getId(): ?int
    {
        return $this->id;
    }

    public function getFirstName(): ?string
    {
        return $this->FirstName;
    }

    public function setFirstName(string $FirstName): static
    {
        $this->FirstName = $FirstName;

        return $this;
    }

    public function getLastName(): ?string
    {
        return $this->LastName;
    }

    public function setLastName(string $LastName): static
    {
        $this->LastName = $LastName;

        return $this;
    }

    public function getAge(): ?int
    {
        return $this->Age;
    }

    public function setAge(int $Age): static
    {
        $this->Age = $Age;

        return $this;
    }

    public function getDateNaissance(): ?\DateTimeImmutable
    {
        return $this->Date_naissance;
    }

    public function setDateNaissance(\DateTimeImmutable $Date_naissance): static
    {
        $this->Date_naissance = $Date_naissance;

        return $this;
    }

    public function getAdresse(): ?string
    {
        return $this->Adresse;
    }

    public function setAdresse(string $Adresse): static
    {
        $this->Adresse = $Adresse;

        return $this;
    }

    public function getDescription(): ?string
    {
        return $this->Description;
    }

    public function setDescription(string $Description): static
    {
        $this->Description = $Description;

        return $this;
    }

    public function getFichePatient(): ?string
    {
        return $this->Fiche_patient;
    }

    public function setFichePatient(string $Fiche_patient): static
    {
        $this->Fiche_patient = $Fiche_patient;

        return $this;
    }

    public function getCreatedAt(): ?\DateTimeImmutable
    {
        return $this->CreatedAt;
    }

    public function setCreatedAt(\DateTimeImmutable $CreatedAt): static
    {
        $this->CreatedAt = $CreatedAt;

        return $this;
    }

    public function getUpdatedAt(): ?\DateTimeImmutable
    {
        return $this->UpdatedAt;
    }

    public function setUpdatedAt(\DateTimeImmutable $UpdatedAt): static
    {
        $this->UpdatedAt = $UpdatedAt;

        return $this;
    }

    public function getPhone(): ?string
    {
        return $this->phone;
    }

    public function setPhone(string $phone): static
    {
        $this->phone = $phone;

        return $this;
    }
}

src/Controller/WelcomeController.php
<?php

namespace App\Controller;

use App\Entity\Contact;
use App\Form\ContactType;
use Doctrine\ORM\EntityManagerInterface;
use Symfony\Component\HttpFoundation\Request;
use Symfony\Component\HttpFoundation\Response;
use Symfony\Component\Routing\Annotation\Route;
use Symfony\Bundle\FrameworkBundle\Controller\AbstractController;

class WelcomeController extends AbstractController
{
    #[Route('/', name: 'welcome.index')]
    public function index(): Response
    {
        return $this->render('welcome/index.html.twig', [
        ]);
    }
    #[Route('/contact', name: 'welcome.contact')]
    public function contact(Request $request, EntityManagerInterface $manager): Response
    {
        $contact = new Contact();
        
        $form = $this->createForm(ContactType::class, $contact);
        $form->handleRequest($request);
        if($form->isSubmitted() && $form->isValid())
        {
            $contact = $form->getData();
            $manager->persist($contact);
            $manager->flush();

            return $this->redirectToRoute("welcome.index");
        }
        

        return $this->render('welcome/contact.html.twig', [
            'form' => $form->createView(),
        ]);
    }
}

templates/welcome/contact.html.twig
{% extends 'base.html.twig' %}

{% block title %}Contactez nous
{% endblock %}

{% block body %}
	<header class="site-header d-flex flex-column justify-content-center align-items-center">
		<div class="container">
			<div class="row align-items-center">

				<div class="col-lg-5 col-12">
					<nav aria-label="breadcrumb">
						<ol class="breadcrumb">
							<li class="breadcrumb-item">
								<a href="{{path('welcome.index')}}">Homepage</a>
							</li>

							<li class="breadcrumb-item active" aria-current="page">Contact Form</li>
						</ol>
					</nav>

					<h2 class="text-white">Contact Form</h2>
				</div>

			</div>
		</div>
	</header>


	<section class="section-padding section-bg">
		<div class="container">
			<div class="row">

				<div class="col-lg-12 col-12">
					<h3 class="mb-4 pb-2">Remplire la formule</h3>
				</div>

				<div class="col-lg-6 col-12">
					<div class="custom-form contact-form" role="form">
						{{ form_start(form) }}
						<div class="row">
							<div class="col-lg-6 col-md-6 col-12">
								<div class="form-floating">
									<input type="text" name="{{field_name(form.Fullname)}}" id="name" class="form-control" placeholder="Nom Complet" required="">

									<label for="floatingInput">Nom Complet</label>
								</div>
							</div>

							<div class="col-lg-6 col-md-6 col-12">
								<div class="form-floating">
									<input type="email" name="{{field_name(form.email)}}" id="email" pattern="[^ @]*@[^ @]*" class="form-control" placeholder="Email address" required="">

									<label for="floatingInput">Email address</label>
								</div>
							</div>

							<div class="col-lg-12 col-12">
								<div class="form-floating">
									<input type="text" name="{{field_name(form.Adresse)}}" id="name" class="form-control" placeholder="Addresse" required="">

									<label for="floatingInput">Addresse</label>
								</div>

								<div class="form-floating">
									<textarea class="form-control" name="{{field_name(form.description)}}" id="message" placeholder="Ecrit nous en details ..."></textarea>

									<label for="floatingTextarea">Sujet du contact</label>
								</div>
							</div>

							<div class="col-lg-4 col-12 ms-auto">
								<button type="submit" class="form-control">Submit</button>
							</div>
							
						</div>
                        {{ form_end(form) }}
					</div>

				</div>
			</section>

		{% endblock %}